services:
  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: abdulaxad
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main-service
    networks:
      - bridge-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U abdulaxad -d main-service" ]
      retries: 3
      interval: 3s
      timeout: 3s


  main-service:
    build:
      context: ./epam-gym-app-main-service
    container_name: main-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    networks:
      - bridge-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/main-service
      SPRING_DATASOURCE_USERNAME: abdulaxad
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_INSTANCE_HOSTNAME: eureka-service
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
      SPRING_ACTIVEMQ_BROKER-URL: tcp://messaging-service:61616
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  trainer-workload-service:
    build:
      context: ./epam-gym-app-trainer-workload-service
    container_name: trainer-workload-service
    ports:
      - '8081:8081'
    networks:
      - bridge-network
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-service
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
      SPRING_ACTIVEMQ_BROKER-URL: tcp://messaging-service:61616
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: mongo-database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  eureka-service:
    build:
      context: ./epam-gym-app-eureka-service
    container_name: eureka-service
    ports:
      - '8761:8761'
    networks:
      - bridge-network
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  messaging-service:
    image: rmohr/activemq:5.15.6
    container_name: messaging-service
    platform: linux/amd64
    ports:
      - '61616:61616'
      - '8161:8161'
    environment:
      USERNAME: admin
      PASSWORD: admin
      ACTIVEMQ_BROKER_NAME: active-mq-broker
    volumes:
      - activemq_data:/opt/activemq/data
    networks:
      - bridge-network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bridge-network
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
      - MONGODB_INITDB_ROOT_DATABASE=mongo-database


  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - bridge-network
  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
       GF_SECURITY_ADMIN_USER: admin
       GF_SECURITY_ADMIN_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      -  grafana-storage:/var/lib/grafana
    networks:
      - bridge-network



networks:
  bridge-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  activemq_data:
    driver: local
  grafana-storage:
    driver: local
  mongodb-data:
    driver: local
