spring:
  application:
    name: epam-gym-app-main-service
  profiles:
    active: dev
  activemq:
    user: admin
    password: admin
    packages:
      trusted:
        - java.lang
        - org.springframework.remoting.support
        - epam/client/dto/*
        - epam/dto/*
    broker-url: tcp://localhost:61616
    trainer-workload-queue: trainer.workload.queue
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99, 0.999

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
training:
  service:
    name: epam-gym-app-trainer-workload-service


