spring:
  profiles:
    active: dev
  application:
    name: epam-gym-app-trainer-workload-service
  data:
    jpa:
      repositories:
        enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081