spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/?authSource=admin
      database: mongo-database
      max-daily-working-hour: 480
application:
  security:
    internal-token:
      issuer: main-service
      audience-id: trainer-workload-service
      keys:
        secret-key: "Y3UJgeJVhg5NaWXypLkC4y0ADrUBfGAxhvGdRdULZivfvzuVtv6AzW6NRuEE6DM9xpoWX4hereyvLS2YPiBTZ8xbB3axdM99LhES"