spring:

  profiles:
    active: dev
  application:
    name: epam-gym-app-trainer-workload-service

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/?authSource=admin
      database: mongo-database
      max-daily-working-hour: 480
      auto-index-creation: true

  activemq:
    user: admin
    password: admin
    packages:
      trusted:
        - java.lang
        - org.springframework.remoting.support
        - epam/client/dto/*
        - epam/dto/*
    broker-url: tcp://localhost:61616
    trainer-workload-summary-queue: trainer.workload.summary.queue
    trainer-workload-daily-summary-queue: trainer.workload.daily.summary.queue

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]