spring:
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:gym;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: abdulaxad
    password: root

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
      jakarta.persistence.sql-load-script-source: classpath:database_initializer/data.sql
    open-in-view: true
  jms:
    cache:
      consumers: false

  data:
    jpa:
      repositories:
        enabled: true
server:
  port: 8080

application:
  security:
    jwt-token:
      access-expiration: 3600000
      refresh-expiration: 15778800000  #  6 months
      keys:
        secret-key: "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0"
    internal-token:
      token-expiration: 1500
      keys:
        secret-key: "Y3UJgeJVhg5NaWXypLkC4y0ADrUBfGAxhvGdRdULZivfvzuVtv6AzW6NRuEE6DM9xpoWX4hereyvLS2YPiBTZ8xbB3axdM99LhES"
      subject-id: main-service
      audience-id: trainer-workload-service
      issuer-id: main-service
eureka:
  client:
    enabled: false