spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epam_gym_app_main_service
    driver-class-name: org.postgresql.Driver
    username: abdulaxad
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      jakarta.persistence.sql-load-script-source: classpath:database_initializer/data.sql
    open-in-view: true
  data:
    jpa:
      repositories:
        enabled: true
server:
  port: 8080

application:
  security:
    jwt-token:
      access-expiration: 3600000
      refresh-expiration: 15778800000  #  6 months
      keys:
        secret-key: "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0"
    internal-token:
      token-expiration: 1500
      keys:
        secret-key: "Y3UJgeJVhg5NaWXypLkC4y0ADrUBfGAxhvGdRdULZivfvzuVtv6AzW6NRuEE6DM9xpoWX4hereyvLS2YPiBTZ8xbB3axdM99LhES"
      subject-id: main-service
      audience-id: trainer-workload-service
      issuer-id: main-service

resilience4j.circuitbreaker:
  instances:
    trainerWorkloadService:
      failureRateThreshold: 50 #the rate of failures to be moved to OPEN position
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10 #consider the last 10 failures
      minimumNumberOfCalls: 5 #consider minimum the last 5 calls
      permittedNumberOfCallsInHalfOpenState: 3 #calls on test stage or HALF-OPEN position
      waitDurationInOpenState: 5s
      slowCallDurationThreshold: 2s
      slowCallRateThreshold: 50 #
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException # 5XX exceptions
        - java.io.IOException #network exceptions
        - java.util.concurrent.TimeoutException
        - java.lang.RuntimeException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException #ignore 4XX exceptions